collections:
  sources:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "sources"
    values:
      layout: "source-description"

exclude:
  - "README.md"
  - "LICENSE.md"
  - "vendor"
  - "Gemfile"
  - "Gemfile.lock"
